// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jujweovweazjrxhzsvnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1andlb3Z3ZWF6anJ4aHpzdm5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMzEyMTgsImV4cCI6MjA1NzgwNzIxOH0.OrloAM7vwC8V2S6xmSmTgI8UonGO59PfxTfiIUPoyKA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);